### ISSUE TITLE
new feature, visit history only for current active editor

### ISSUE THREAD

**Issue by t9md** [t9md/atom-cursor-history#11]
Suggested by @tmunro.

Whats appropriate command name, I like short name if its make sense.
### Across text-editors
- `cursor-history:next`
- `cursor-history:prev`
### Pick entry for current active text-editor(having same URI or path).
-  `cursor-history:next-within-editor`
- `cursor-history:prev-within-editor`

?
`next-in-editor`?, `next-for-current-editor`??

**Comment by tmunro** [comment]
I think `within-editor` makes sense, I'd go for that.

**Comment by t9md** [comment]
Thanks, just released v0.5.0.
Was very tough time to rewrite completely, but I'm very happy now.
Thanks for nice feature suggestion.
