### ISSUE TITLE
[feature request] Mouse button support

### ISSUE THREAD

**Issue by bluebruce** [t9md/atom-cursor-history#13]
It will be great if one can use mouse button 3 and 4 (configurable) to do the jump back/forward.

**Comment by t9md** [comment]
I dont' use mouse usually while editing, so I myself have no motivation to support mouse currently.

But anyway I wont add this by myself, if someone made pull request, I will check.
I'm OK if adding this feature don't introduce big complexity to current code base.

**Comment by bluebruce** [comment]
@t9md, This atom package is the best one of the kind I can find to fit into my workflow. Since I'm not capable of providing a pull request (for now), this feedback is a thanks to you and hopefully you can keep improving this great package.

**Comment by t9md** [comment]
Thanks! This kind of feedback really motivate me.
For mouse, i want support. But as you can see im my atom.io profile, Im maintaining lots of packages, so Im getting conservatve to add feature Im wont activelly use.

I hope you chek my other package like quick-highlight, project-folder etc..

**Comment by bluebruce** [comment]
Ha~ Didn't I mention that 'quick-highlight' is another one of my favorite. :)

**Comment by t9md** [comment]
Oh, ok,, Im happy to hear that.
