### ISSUE TITLE
Checked items in TODO already done? It's confusing to leave them there...

### ISSUE THREAD

**Issue by ghost** [t9md/atom-cursor-history#14]
Thank you for this package. :)

Are the checked items in TODO already done? If so, it's confusing to leave them there... It's better to remove them, or maybe move them to the Features section.

The way it is now, at first glance (like happened to me when looking at https://atom.io/packages/cursor-history) it seems those **are currently** TODO items — i.e., items still to be done. :)

**Comment by ghost** [comment]
BTW, thinking that all those **were** TODO items, I was thinking of not installing this package... Thinking it was not mature enough yet...

**Comment by ghost** [comment]
Why do you close this issue without saying a word?...

**Comment by t9md** [comment]
I'll update doc if I have time, but I don think its confusing since its CHECKED.
I have busy for other task, I don thinks this issue is important.

**Comment by ghost** [comment]
OK. Gotcha. :)
