### ISSUE TITLE
When an open file (buffer) is reopened, it loses the *last* cursor position

### ISSUE THREAD

**Issue by ghost** [t9md/atom-cursor-history#15]
It seems that when an open file (buffer) is reopened, it loses last cursor position...

That is:
1 - When file is reopened (and already open), the cursor goes to 1,1 position ( standard Atom behavior, I think ).
2 - If I choose the Go Previous command, it doesn't go to the previous position... (goes to another one).

Can you see what's going on?

**Comment by t9md** [comment]
Sorry I couldn't understand your original issue, so just not responded.
The codebase greatly changed from you opened this issue, if you have still problem, reopen with precise command and sample text you can repro issue.
