### ISSUE TITLE
flash on land type line doesn't work

### ISSUE THREAD

**Issue by dragonxlwang** [t9md/atom-cursor-history#17]
It works perfectly when flashing by point/word, but not for lines as showed by the gif animation ...

**Comment by t9md** [comment]
Humm, I can't reproduce it. I can highlight line without problem..
Need more detail.

**Comment by t9md** [comment]
Do you have `useShadowDOM` disabled? is so above commit fix your issue.

**Comment by t9md** [comment]
Pls reopen if its still issue.
