### ISSUE TITLE
It would be nice to have auto-scroll to position when file is opened

### ISSUE THREAD

**Issue by tonatiuh** [t9md/atom-cursor-history#19]
Currently, when you open a file the cursor is at the position where it was the last time the file was opened, however, the part of the file that is visible is always the top part of the file. It would be nice if besides keeping the file position, the file were auto-scrolled to where the scroll is at.

**Comment by tonatiuh** [comment]
Thanks for the package btw!

**Comment by t9md** [comment]
Sorry I can't understand your request.
Do you want to keep scrollTop as long as cursor position, and also restore scrollTop when cursor position restored?

**Comment by tonatiuh** [comment]
That's is correct @t9md. 

Let's say I open a file of 1000 lines, I go to the end of the file, then I close the file. The next time I open the file what I will see in the screen is the top of the file despite the cursor is at line 1000.

The way I think the experience will be better is if when I open the file I see the bottom of the file.

**Comment by t9md** [comment]
OK, understand your request, and I want to support these functionalities.
But not quick and easy way since this package don't remember position when file is closed.

I thinks what you want is [remember-file-positions](https://atom.io/packages/remember-file-positions)

**Comment by t9md** [comment]
Postponed.
Use remember-file-positions.
