### ISSUE TITLE
Doesn't work on temporary buffers & weird file paths

### ISSUE THREAD

**Issue by chenglou** [t9md/atom-cursor-history#26]
Temporary buffers would be a nice plus.

By "weird file paths", I have a slightly edge-casy use-case: I work with remote files (through nuclide's [remote feature](https://nuclide.io/docs/quick-start/getting-started/#remote-connection)). The paths are a bit different (e.g. nuclide://foo/bar.js), so I think cursor-history gets confused.

**Comment by t9md** [comment]
duplicate of #16 

This is old feature enhancement request, but I haven't tried to implement it.
Don't wanted to make code-base complex.
I was just lazy to setup environment to understand how it works.

I'll start thinking from temporary buffer support.

If you have conceptual idea for how-you-want-it-expected-to-work please give me input.

**Comment by chenglou** [comment]
Ah oops, closing this then, thanks!
