### ISSUE TITLE
Leak subscriptions

### ISSUE THREAD

**Issue by aki77** [t9md/atom-cursor-history#4]
Please check.

[![Gyazo](http://i.gyazo.com/ebfab960b777b37d29e9c00e59407989.gif)](http://gyazo.com/ebfab960b777b37d29e9c00e59407989)

**Comment by t9md** [comment]
Oh, thanks, I didn't know the way to check subscription leak you reported.
Thanks for that, I will check.

**Comment by aki77** [comment]
Thank you!

[similar problem](https://github.com/atom/whitespace/pull/74)

**Comment by t9md** [comment]
Let me check, the reason you are saying 'Leak' is for very large number like 177 or 185 or disposable increased after opening file?
For every TextEditor instance, cursor-history add subscription to monitor cursor position change, so increasing disposable itself is not issue.

Anyway I should dispose subscription each time TextEditor destroyed, current implementation is not doing this. 
Maybe separate subscription management is required.

Oh, I'll check similar problem you just posted thanks again.

**Comment by t9md** [comment]
I read similar problem issue. Understood problem, I'll fix that.

**Comment by t9md** [comment]
Thanks for report, I believe its fixed!

**Comment by aki77** [comment]
Thanks for awesome package!

**Comment by t9md** [comment]
Oh, you use my package, I'm very glad to know, thanks!.
