### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by DavidLGoldberg** [t9md/atom-cursor-history#9]
Hi! @t9md 

Remember me from Jumpy?

I was just curious if this is still working?  I've wanted to make something like this for sometime, and figured I'd just I use yours if I can get it going!

I tried the aliases, couldn't get that to work, so, I tried cmd shift p to run the commands, but the cursor doesn't jump.

I don't see any errors, checked console etc.

Any ideas?  I reloaded the editor of course heh.

Although I should check your code, just curious, do you use a notion of debouncing for the cursors.  Or is the history every single cursor?  I've wanted to do this with a debounce, so they would have a more meaningful historical footprint (might not matter so much not sure).

-David

**Comment by DavidLGoldberg** [comment]
So, I ran your :clear command and it started working.

Maybe it's not being initialized properly?

Also, I'm using vim-mode and when I select with the mouse on 3 different words, it doesn't seem to remember the mouse clicks in order.  Is there something I have to have the cursor start registering.  The previous / forwards, seem pretty arbitrary.  I can't figure out the pattern.  (Code looked pretty involved).  Should it work with mouse clicks?

**Comment by t9md** [comment]
Strange behavior.
What is `:clear` command?
Still working? Yes I use frequantely in daily coding.
Yes work for mouse click.
By default line delta between moved position exceed 4, it store history.
You can configure that.
This is explained in readme.

Maybe your mouse click is not exceed line delta threshold to save history.

**Comment by DavidLGoldberg** [comment]
Ah, I'll take another look thanks!
